name: Build documentation and deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          # WARNING: The scripts sphinx-apidoc, sphinx-autogen, sphinx-build and sphinx-quickstart are installed in '/home/runner/.local/bin' which is not on PATH.

      - name: Build documentation
        run: |
          # use sphinx to build the documentation
          # 
          #/home/runner/.local/bin/sphinx-build -b html ./docs/source ./docs/build
          sphinx-build -b html ./docs/source ./docs/build
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: ./docs/build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
