# This workflow will install all necessary Python dependencies and run the unit tests

name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: [3.8]
        container:
        - 'python:3.6-slim'
        - 'python:3.7-slim'
        - 'python:3.8-slim'
        - 'python:3.9-slim'
        - 'python:3.10-slim'
        - 'python:3.11-slim'

    container: ${{ matrix.container }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage codecov

    - name: Test with pytest
      run: |
        # run tests with coverage and pytest
        coverage run -m pytest
        coverage report -m
        coverage html
        codecov -t ${{ secrets.CODECOV_TOKEN }}
